//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 03:20:59 PM CEST 
//


package com.karumien.client.adochazka.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfUzivatel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfUzivatel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Uzivatel" type="{http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer}Uzivatel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfUzivatel", propOrder = {
    "uzivatel"
})
public class ArrayOfUzivatel {

    @XmlElement(name = "Uzivatel", nillable = true)
    protected List<Uzivatel> uzivatel;

    /**
     * Gets the value of the uzivatel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uzivatel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUzivatel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Uzivatel }
     * 
     * 
     */
    public List<Uzivatel> getUzivatel() {
        if (uzivatel == null) {
            uzivatel = new ArrayList<Uzivatel>();
        }
        return this.uzivatel;
    }

}
