//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.08 at 07:44:31 PM CEST 
//


package com.karumien.client.adochazka.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CustomerDataDen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerDataDen"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Atributy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Balanc" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemAbsence" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemAbsenceOmluvena" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemDarovaniKrve" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemDovolena" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemFiremniVolno" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemHomeOffice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemJednani" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemKoureni" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemLekar" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemNaPracovisti" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemNahradniVolno" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemNemoc" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemNeplaceneVolno" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemOsetrovaniClenaRodiny" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemPohreb" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemPrace" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemPrekazka" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemPrekazka60" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemPrescas" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemPrestavka" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemSickDay" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemSluzebniCesta" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="CelkemSvatba" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="DenUzavren" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Fond" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="JeNenulovy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="JeSvatek" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="JeVikend" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="KategorieNazev" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KategoriePrirazenaManualne" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Kategorie_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NahradaSvatek" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="NeuznanyPrescas" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Odchod" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PocetZaznamu" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="PovolenyPrescas" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="PovolitPrescas" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Poznamka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PraceNedele" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="PraceNocni" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="PraceOdpoledni" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="PraceSobota" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="PraceSvatek" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Prichod" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="SkutecnyOdchod" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="SkutecnyPrichod" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="TypDochazkaDen" type="{http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models}TypDochazkaDen" minOccurs="0"/&gt;
 *         &lt;element name="ZapocitatSvatek" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerDataDen", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", propOrder = {
    "atributy",
    "balanc",
    "celkemAbsence",
    "celkemAbsenceOmluvena",
    "celkemDarovaniKrve",
    "celkemDovolena",
    "celkemFiremniVolno",
    "celkemHomeOffice",
    "celkemJednani",
    "celkemKoureni",
    "celkemLekar",
    "celkemNaPracovisti",
    "celkemNahradniVolno",
    "celkemNemoc",
    "celkemNeplaceneVolno",
    "celkemOsetrovaniClenaRodiny",
    "celkemPohreb",
    "celkemPrace",
    "celkemPrekazka",
    "celkemPrekazka60",
    "celkemPrescas",
    "celkemPrestavka",
    "celkemSickDay",
    "celkemSluzebniCesta",
    "celkemSvatba",
    "datum",
    "denUzavren",
    "fond",
    "jeNenulovy",
    "jeSvatek",
    "jeVikend",
    "kategorieNazev",
    "kategoriePrirazenaManualne",
    "kategorieId",
    "nahradaSvatek",
    "neuznanyPrescas",
    "odchod",
    "pocetZaznamu",
    "povolenyPrescas",
    "povolitPrescas",
    "poznamka",
    "praceNedele",
    "praceNocni",
    "praceOdpoledni",
    "praceSobota",
    "praceSvatek",
    "prichod",
    "skutecnyOdchod",
    "skutecnyPrichod",
    "typDochazkaDen",
    "zapocitatSvatek"
})
public class CustomerDataDen {

    @XmlElementRef(name = "Atributy", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> atributy;
    @XmlElement(name = "Balanc")
    protected Double balanc;
    @XmlElement(name = "CelkemAbsence")
    protected Double celkemAbsence;
    @XmlElement(name = "CelkemAbsenceOmluvena")
    protected Double celkemAbsenceOmluvena;
    @XmlElement(name = "CelkemDarovaniKrve")
    protected Double celkemDarovaniKrve;
    @XmlElement(name = "CelkemDovolena")
    protected Double celkemDovolena;
    @XmlElement(name = "CelkemFiremniVolno")
    protected Double celkemFiremniVolno;
    @XmlElement(name = "CelkemHomeOffice")
    protected Double celkemHomeOffice;
    @XmlElement(name = "CelkemJednani")
    protected Double celkemJednani;
    @XmlElement(name = "CelkemKoureni")
    protected Double celkemKoureni;
    @XmlElement(name = "CelkemLekar")
    protected Double celkemLekar;
    @XmlElement(name = "CelkemNaPracovisti")
    protected Double celkemNaPracovisti;
    @XmlElement(name = "CelkemNahradniVolno")
    protected Double celkemNahradniVolno;
    @XmlElement(name = "CelkemNemoc")
    protected Double celkemNemoc;
    @XmlElement(name = "CelkemNeplaceneVolno")
    protected Double celkemNeplaceneVolno;
    @XmlElement(name = "CelkemOsetrovaniClenaRodiny")
    protected Double celkemOsetrovaniClenaRodiny;
    @XmlElement(name = "CelkemPohreb")
    protected Double celkemPohreb;
    @XmlElement(name = "CelkemPrace")
    protected Double celkemPrace;
    @XmlElement(name = "CelkemPrekazka")
    protected Double celkemPrekazka;
    @XmlElement(name = "CelkemPrekazka60")
    protected Double celkemPrekazka60;
    @XmlElement(name = "CelkemPrescas")
    protected Double celkemPrescas;
    @XmlElement(name = "CelkemPrestavka")
    protected Double celkemPrestavka;
    @XmlElement(name = "CelkemSickDay")
    protected Double celkemSickDay;
    @XmlElement(name = "CelkemSluzebniCesta")
    protected Double celkemSluzebniCesta;
    @XmlElement(name = "CelkemSvatba")
    protected Double celkemSvatba;
    @XmlElement(name = "Datum")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datum;
    @XmlElement(name = "DenUzavren")
    protected Boolean denUzavren;
    @XmlElement(name = "Fond")
    protected Double fond;
    @XmlElement(name = "JeNenulovy")
    protected Boolean jeNenulovy;
    @XmlElement(name = "JeSvatek")
    protected Boolean jeSvatek;
    @XmlElement(name = "JeVikend")
    protected Boolean jeVikend;
    @XmlElementRef(name = "KategorieNazev", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> kategorieNazev;
    @XmlElement(name = "KategoriePrirazenaManualne")
    protected Boolean kategoriePrirazenaManualne;
    @XmlElementRef(name = "Kategorie_Id", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> kategorieId;
    @XmlElement(name = "NahradaSvatek")
    protected Double nahradaSvatek;
    @XmlElement(name = "NeuznanyPrescas")
    protected Double neuznanyPrescas;
    @XmlElementRef(name = "Odchod", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> odchod;
    @XmlElement(name = "PocetZaznamu")
    protected Integer pocetZaznamu;
    @XmlElement(name = "PovolenyPrescas")
    protected Double povolenyPrescas;
    @XmlElementRef(name = "PovolitPrescas", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> povolitPrescas;
    @XmlElementRef(name = "Poznamka", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> poznamka;
    @XmlElement(name = "PraceNedele")
    protected Double praceNedele;
    @XmlElement(name = "PraceNocni")
    protected Double praceNocni;
    @XmlElement(name = "PraceOdpoledni")
    protected Double praceOdpoledni;
    @XmlElement(name = "PraceSobota")
    protected Double praceSobota;
    @XmlElement(name = "PraceSvatek")
    protected Double praceSvatek;
    @XmlElementRef(name = "Prichod", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> prichod;
    @XmlElementRef(name = "SkutecnyOdchod", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> skutecnyOdchod;
    @XmlElementRef(name = "SkutecnyPrichod", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> skutecnyPrichod;
    @XmlElement(name = "TypDochazkaDen")
    @XmlSchemaType(name = "string")
    protected TypDochazkaDen typDochazkaDen;
    @XmlElementRef(name = "ZapocitatSvatek", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceWS.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> zapocitatSvatek;

    /**
     * Gets the value of the atributy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAtributy() {
        return atributy;
    }

    /**
     * Sets the value of the atributy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAtributy(JAXBElement<String> value) {
        this.atributy = value;
    }

    /**
     * Gets the value of the balanc property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBalanc() {
        return balanc;
    }

    /**
     * Sets the value of the balanc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBalanc(Double value) {
        this.balanc = value;
    }

    /**
     * Gets the value of the celkemAbsence property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemAbsence() {
        return celkemAbsence;
    }

    /**
     * Sets the value of the celkemAbsence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemAbsence(Double value) {
        this.celkemAbsence = value;
    }

    /**
     * Gets the value of the celkemAbsenceOmluvena property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemAbsenceOmluvena() {
        return celkemAbsenceOmluvena;
    }

    /**
     * Sets the value of the celkemAbsenceOmluvena property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemAbsenceOmluvena(Double value) {
        this.celkemAbsenceOmluvena = value;
    }

    /**
     * Gets the value of the celkemDarovaniKrve property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemDarovaniKrve() {
        return celkemDarovaniKrve;
    }

    /**
     * Sets the value of the celkemDarovaniKrve property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemDarovaniKrve(Double value) {
        this.celkemDarovaniKrve = value;
    }

    /**
     * Gets the value of the celkemDovolena property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemDovolena() {
        return celkemDovolena;
    }

    /**
     * Sets the value of the celkemDovolena property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemDovolena(Double value) {
        this.celkemDovolena = value;
    }

    /**
     * Gets the value of the celkemFiremniVolno property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemFiremniVolno() {
        return celkemFiremniVolno;
    }

    /**
     * Sets the value of the celkemFiremniVolno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemFiremniVolno(Double value) {
        this.celkemFiremniVolno = value;
    }

    /**
     * Gets the value of the celkemHomeOffice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemHomeOffice() {
        return celkemHomeOffice;
    }

    /**
     * Sets the value of the celkemHomeOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemHomeOffice(Double value) {
        this.celkemHomeOffice = value;
    }

    /**
     * Gets the value of the celkemJednani property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemJednani() {
        return celkemJednani;
    }

    /**
     * Sets the value of the celkemJednani property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemJednani(Double value) {
        this.celkemJednani = value;
    }

    /**
     * Gets the value of the celkemKoureni property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemKoureni() {
        return celkemKoureni;
    }

    /**
     * Sets the value of the celkemKoureni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemKoureni(Double value) {
        this.celkemKoureni = value;
    }

    /**
     * Gets the value of the celkemLekar property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemLekar() {
        return celkemLekar;
    }

    /**
     * Sets the value of the celkemLekar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemLekar(Double value) {
        this.celkemLekar = value;
    }

    /**
     * Gets the value of the celkemNaPracovisti property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemNaPracovisti() {
        return celkemNaPracovisti;
    }

    /**
     * Sets the value of the celkemNaPracovisti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemNaPracovisti(Double value) {
        this.celkemNaPracovisti = value;
    }

    /**
     * Gets the value of the celkemNahradniVolno property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemNahradniVolno() {
        return celkemNahradniVolno;
    }

    /**
     * Sets the value of the celkemNahradniVolno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemNahradniVolno(Double value) {
        this.celkemNahradniVolno = value;
    }

    /**
     * Gets the value of the celkemNemoc property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemNemoc() {
        return celkemNemoc;
    }

    /**
     * Sets the value of the celkemNemoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemNemoc(Double value) {
        this.celkemNemoc = value;
    }

    /**
     * Gets the value of the celkemNeplaceneVolno property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemNeplaceneVolno() {
        return celkemNeplaceneVolno;
    }

    /**
     * Sets the value of the celkemNeplaceneVolno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemNeplaceneVolno(Double value) {
        this.celkemNeplaceneVolno = value;
    }

    /**
     * Gets the value of the celkemOsetrovaniClenaRodiny property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemOsetrovaniClenaRodiny() {
        return celkemOsetrovaniClenaRodiny;
    }

    /**
     * Sets the value of the celkemOsetrovaniClenaRodiny property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemOsetrovaniClenaRodiny(Double value) {
        this.celkemOsetrovaniClenaRodiny = value;
    }

    /**
     * Gets the value of the celkemPohreb property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemPohreb() {
        return celkemPohreb;
    }

    /**
     * Sets the value of the celkemPohreb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemPohreb(Double value) {
        this.celkemPohreb = value;
    }

    /**
     * Gets the value of the celkemPrace property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemPrace() {
        return celkemPrace;
    }

    /**
     * Sets the value of the celkemPrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemPrace(Double value) {
        this.celkemPrace = value;
    }

    /**
     * Gets the value of the celkemPrekazka property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemPrekazka() {
        return celkemPrekazka;
    }

    /**
     * Sets the value of the celkemPrekazka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemPrekazka(Double value) {
        this.celkemPrekazka = value;
    }

    /**
     * Gets the value of the celkemPrekazka60 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemPrekazka60() {
        return celkemPrekazka60;
    }

    /**
     * Sets the value of the celkemPrekazka60 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemPrekazka60(Double value) {
        this.celkemPrekazka60 = value;
    }

    /**
     * Gets the value of the celkemPrescas property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemPrescas() {
        return celkemPrescas;
    }

    /**
     * Sets the value of the celkemPrescas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemPrescas(Double value) {
        this.celkemPrescas = value;
    }

    /**
     * Gets the value of the celkemPrestavka property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemPrestavka() {
        return celkemPrestavka;
    }

    /**
     * Sets the value of the celkemPrestavka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemPrestavka(Double value) {
        this.celkemPrestavka = value;
    }

    /**
     * Gets the value of the celkemSickDay property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemSickDay() {
        return celkemSickDay;
    }

    /**
     * Sets the value of the celkemSickDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemSickDay(Double value) {
        this.celkemSickDay = value;
    }

    /**
     * Gets the value of the celkemSluzebniCesta property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemSluzebniCesta() {
        return celkemSluzebniCesta;
    }

    /**
     * Sets the value of the celkemSluzebniCesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemSluzebniCesta(Double value) {
        this.celkemSluzebniCesta = value;
    }

    /**
     * Gets the value of the celkemSvatba property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCelkemSvatba() {
        return celkemSvatba;
    }

    /**
     * Sets the value of the celkemSvatba property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCelkemSvatba(Double value) {
        this.celkemSvatba = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the denUzavren property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDenUzavren() {
        return denUzavren;
    }

    /**
     * Sets the value of the denUzavren property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDenUzavren(Boolean value) {
        this.denUzavren = value;
    }

    /**
     * Gets the value of the fond property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFond() {
        return fond;
    }

    /**
     * Sets the value of the fond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFond(Double value) {
        this.fond = value;
    }

    /**
     * Gets the value of the jeNenulovy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isJeNenulovy() {
        return jeNenulovy;
    }

    /**
     * Sets the value of the jeNenulovy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJeNenulovy(Boolean value) {
        this.jeNenulovy = value;
    }

    /**
     * Gets the value of the jeSvatek property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isJeSvatek() {
        return jeSvatek;
    }

    /**
     * Sets the value of the jeSvatek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJeSvatek(Boolean value) {
        this.jeSvatek = value;
    }

    /**
     * Gets the value of the jeVikend property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isJeVikend() {
        return jeVikend;
    }

    /**
     * Sets the value of the jeVikend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJeVikend(Boolean value) {
        this.jeVikend = value;
    }

    /**
     * Gets the value of the kategorieNazev property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getKategorieNazev() {
        return kategorieNazev;
    }

    /**
     * Sets the value of the kategorieNazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setKategorieNazev(JAXBElement<String> value) {
        this.kategorieNazev = value;
    }

    /**
     * Gets the value of the kategoriePrirazenaManualne property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKategoriePrirazenaManualne() {
        return kategoriePrirazenaManualne;
    }

    /**
     * Sets the value of the kategoriePrirazenaManualne property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKategoriePrirazenaManualne(Boolean value) {
        this.kategoriePrirazenaManualne = value;
    }

    /**
     * Gets the value of the kategorieId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getKategorieId() {
        return kategorieId;
    }

    /**
     * Sets the value of the kategorieId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setKategorieId(JAXBElement<Integer> value) {
        this.kategorieId = value;
    }

    /**
     * Gets the value of the nahradaSvatek property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNahradaSvatek() {
        return nahradaSvatek;
    }

    /**
     * Sets the value of the nahradaSvatek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNahradaSvatek(Double value) {
        this.nahradaSvatek = value;
    }

    /**
     * Gets the value of the neuznanyPrescas property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNeuznanyPrescas() {
        return neuznanyPrescas;
    }

    /**
     * Sets the value of the neuznanyPrescas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNeuznanyPrescas(Double value) {
        this.neuznanyPrescas = value;
    }

    /**
     * Gets the value of the odchod property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getOdchod() {
        return odchod;
    }

    /**
     * Sets the value of the odchod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setOdchod(JAXBElement<XMLGregorianCalendar> value) {
        this.odchod = value;
    }

    /**
     * Gets the value of the pocetZaznamu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPocetZaznamu() {
        return pocetZaznamu;
    }

    /**
     * Sets the value of the pocetZaznamu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPocetZaznamu(Integer value) {
        this.pocetZaznamu = value;
    }

    /**
     * Gets the value of the povolenyPrescas property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPovolenyPrescas() {
        return povolenyPrescas;
    }

    /**
     * Sets the value of the povolenyPrescas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPovolenyPrescas(Double value) {
        this.povolenyPrescas = value;
    }

    /**
     * Gets the value of the povolitPrescas property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getPovolitPrescas() {
        return povolitPrescas;
    }

    /**
     * Sets the value of the povolitPrescas property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setPovolitPrescas(JAXBElement<Boolean> value) {
        this.povolitPrescas = value;
    }

    /**
     * Gets the value of the poznamka property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPoznamka() {
        return poznamka;
    }

    /**
     * Sets the value of the poznamka property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPoznamka(JAXBElement<String> value) {
        this.poznamka = value;
    }

    /**
     * Gets the value of the praceNedele property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPraceNedele() {
        return praceNedele;
    }

    /**
     * Sets the value of the praceNedele property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPraceNedele(Double value) {
        this.praceNedele = value;
    }

    /**
     * Gets the value of the praceNocni property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPraceNocni() {
        return praceNocni;
    }

    /**
     * Sets the value of the praceNocni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPraceNocni(Double value) {
        this.praceNocni = value;
    }

    /**
     * Gets the value of the praceOdpoledni property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPraceOdpoledni() {
        return praceOdpoledni;
    }

    /**
     * Sets the value of the praceOdpoledni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPraceOdpoledni(Double value) {
        this.praceOdpoledni = value;
    }

    /**
     * Gets the value of the praceSobota property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPraceSobota() {
        return praceSobota;
    }

    /**
     * Sets the value of the praceSobota property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPraceSobota(Double value) {
        this.praceSobota = value;
    }

    /**
     * Gets the value of the praceSvatek property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPraceSvatek() {
        return praceSvatek;
    }

    /**
     * Sets the value of the praceSvatek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPraceSvatek(Double value) {
        this.praceSvatek = value;
    }

    /**
     * Gets the value of the prichod property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getPrichod() {
        return prichod;
    }

    /**
     * Sets the value of the prichod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setPrichod(JAXBElement<XMLGregorianCalendar> value) {
        this.prichod = value;
    }

    /**
     * Gets the value of the skutecnyOdchod property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getSkutecnyOdchod() {
        return skutecnyOdchod;
    }

    /**
     * Sets the value of the skutecnyOdchod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setSkutecnyOdchod(JAXBElement<XMLGregorianCalendar> value) {
        this.skutecnyOdchod = value;
    }

    /**
     * Gets the value of the skutecnyPrichod property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getSkutecnyPrichod() {
        return skutecnyPrichod;
    }

    /**
     * Sets the value of the skutecnyPrichod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setSkutecnyPrichod(JAXBElement<XMLGregorianCalendar> value) {
        this.skutecnyPrichod = value;
    }

    /**
     * Gets the value of the typDochazkaDen property.
     * 
     * @return
     *     possible object is
     *     {@link TypDochazkaDen }
     *     
     */
    public TypDochazkaDen getTypDochazkaDen() {
        return typDochazkaDen;
    }

    /**
     * Sets the value of the typDochazkaDen property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypDochazkaDen }
     *     
     */
    public void setTypDochazkaDen(TypDochazkaDen value) {
        this.typDochazkaDen = value;
    }

    /**
     * Gets the value of the zapocitatSvatek property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getZapocitatSvatek() {
        return zapocitatSvatek;
    }

    /**
     * Sets the value of the zapocitatSvatek property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setZapocitatSvatek(JAXBElement<Boolean> value) {
        this.zapocitatSvatek = value;
    }

}
