//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 03:20:59 PM CEST 
//


package com.karumien.client.adochazka.schemas;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.karumien.client.adochazka.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private final static QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private final static QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private final static QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private final static QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private final static QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private final static QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private final static QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private final static QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private final static QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private final static QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private final static QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
    private final static QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private final static QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private final static QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private final static QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private final static QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private final static QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private final static QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private final static QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private final static QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
    private final static QName _CustomerDataPristupy_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "CustomerDataPristupy");
    private final static QName _ArrayOfPristup_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "ArrayOfPristup");
    private final static QName _Pristup_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Pristup");
    private final static QName _CustomerDataDochazka_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "CustomerDataDochazka");
    private final static QName _ArrayOfDochazka_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "ArrayOfDochazka");
    private final static QName _Dochazka_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Dochazka");
    private final static QName _CustomerDataUzivatele_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "CustomerDataUzivatele");
    private final static QName _ArrayOfUzivatel_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "ArrayOfUzivatel");
    private final static QName _Uzivatel_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Uzivatel");
    private final static QName _ArrayOfKategorie_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "ArrayOfKategorie");
    private final static QName _Kategorie_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Kategorie");
    private final static QName _ArrayOfOddeleni_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "ArrayOfOddeleni");
    private final static QName _Oddeleni_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Oddeleni");
    private final static QName _CustomerDataPritomnost_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "CustomerDataPritomnost");
    private final static QName _ArrayOfPritomnost_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "ArrayOfPritomnost");
    private final static QName _Pritomnost_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Pritomnost");
    private final static QName _TypVerifikace_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models", "TypVerifikace");
    private final static QName _TypCinnosti_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models", "TypCinnosti");
    private final static QName _TypUzivatele_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models", "TypUzivatele");
    private final static QName _VratPristupyID_QNAME = new QName("http://schemas.holypos.com/holyattendance", "ID");
    private final static QName _VratPristupyHeslo_QNAME = new QName("http://schemas.holypos.com/holyattendance", "heslo");
    private final static QName _VratPristupyResponseVratPristupyResult_QNAME = new QName("http://schemas.holypos.com/holyattendance", "VratPristupyResult");
    private final static QName _VratDochazkuResponseVratDochazkuResult_QNAME = new QName("http://schemas.holypos.com/holyattendance", "VratDochazkuResult");
    private final static QName _VratUzivateleResponseVratUzivateleResult_QNAME = new QName("http://schemas.holypos.com/holyattendance", "VratUzivateleResult");
    private final static QName _VratPritomnostResponseVratPritomnostResult_QNAME = new QName("http://schemas.holypos.com/holyattendance", "VratPritomnostResult");
    private final static QName _PritomnostCinnostNazev_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "CinnostNazev");
    private final static QName _PritomnostKategorieId_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "KategorieId");
    private final static QName _PritomnostKategorieNazev_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "KategorieNazev");
    private final static QName _PritomnostOddeleniString_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "OddeleniString");
    private final static QName _PritomnostPrichod_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Prichod");
    private final static QName _PritomnostTerminalId_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "TerminalId");
    private final static QName _PritomnostTerminalNazev_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "TerminalNazev");
    private final static QName _PritomnostUzivatelCislo_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "UzivatelCislo");
    private final static QName _PritomnostUzivatelJmeno_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "UzivatelJmeno");
    private final static QName _PritomnostUzivatelPrijmeni_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "UzivatelPrijmeni");
    private final static QName _OddeleniNazev_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Nazev");
    private final static QName _UzivatelCislo_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Cislo");
    private final static QName _UzivatelDatumNarozeni_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "DatumNarozeni");
    private final static QName _UzivatelEMail_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "EMail");
    private final static QName _UzivatelHeslo_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Heslo");
    private final static QName _UzivatelHodinovaSazba_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "HodinovaSazba");
    private final static QName _UzivatelJmeno_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Jmeno");
    private final static QName _UzivatelKarta_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Karta");
    private final static QName _UzivatelPrijmeni_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Prijmeni");
    private final static QName _UzivatelTelefon_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Telefon");
    private final static QName _UzivatelTypUzivatele_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "TypUzivatele");
    private final static QName _DochazkaDatumOdchod_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "DatumOdchod");
    private final static QName _DochazkaDatumOdchodSkutecny_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "DatumOdchodSkutecny");
    private final static QName _DochazkaDatumPrichod_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "DatumPrichod");
    private final static QName _DochazkaDatumPrichodSkutecny_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "DatumPrichodSkutecny");
    private final static QName _DochazkaDochazkaDenId_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "DochazkaDen_Id");
    private final static QName _DochazkaPoznamka_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Poznamka");
    private final static QName _DochazkaTypUzivatelskeCinnostiId_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "TypUzivatelskeCinnosti_Id");
    private final static QName _DochazkaUzivatelId_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Uzivatel_Id");
    private final static QName _PristupCisloUzivatele_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "CisloUzivatele");
    private final static QName _PristupDochazkaId_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Dochazka_Id");
    private final static QName _PristupKartaUzivatele_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "KartaUzivatele");
    private final static QName _PristupKlavesa1_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Klavesa1");
    private final static QName _PristupKlavesa2_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Klavesa2");
    private final static QName _PristupKodPrace_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "KodPrace");
    private final static QName _PristupVytvorilUzivatelId_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "VytvorilUzivatel_Id");
    private final static QName _CustomerDataUzivateleUzivatele_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Uzivatele");
    private final static QName _CustomerDataPristupyPristupy_QNAME = new QName("http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", "Pristupy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.karumien.client.adochazka.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

    /**
     * Create an instance of {@link VratPristupy }
     * 
     */
    public VratPristupy createVratPristupy() {
        return new VratPristupy();
    }

    /**
     * Create an instance of {@link VratPristupyResponse }
     * 
     */
    public VratPristupyResponse createVratPristupyResponse() {
        return new VratPristupyResponse();
    }

    /**
     * Create an instance of {@link CustomerDataPristupy }
     * 
     */
    public CustomerDataPristupy createCustomerDataPristupy() {
        return new CustomerDataPristupy();
    }

    /**
     * Create an instance of {@link VratDochazku }
     * 
     */
    public VratDochazku createVratDochazku() {
        return new VratDochazku();
    }

    /**
     * Create an instance of {@link VratDochazkuResponse }
     * 
     */
    public VratDochazkuResponse createVratDochazkuResponse() {
        return new VratDochazkuResponse();
    }

    /**
     * Create an instance of {@link CustomerDataDochazka }
     * 
     */
    public CustomerDataDochazka createCustomerDataDochazka() {
        return new CustomerDataDochazka();
    }

    /**
     * Create an instance of {@link VratUzivatele }
     * 
     */
    public VratUzivatele createVratUzivatele() {
        return new VratUzivatele();
    }

    /**
     * Create an instance of {@link VratUzivateleResponse }
     * 
     */
    public VratUzivateleResponse createVratUzivateleResponse() {
        return new VratUzivateleResponse();
    }

    /**
     * Create an instance of {@link CustomerDataUzivatele }
     * 
     */
    public CustomerDataUzivatele createCustomerDataUzivatele() {
        return new CustomerDataUzivatele();
    }

    /**
     * Create an instance of {@link VratPritomnost }
     * 
     */
    public VratPritomnost createVratPritomnost() {
        return new VratPritomnost();
    }

    /**
     * Create an instance of {@link VratPritomnostResponse }
     * 
     */
    public VratPritomnostResponse createVratPritomnostResponse() {
        return new VratPritomnostResponse();
    }

    /**
     * Create an instance of {@link CustomerDataPritomnost }
     * 
     */
    public CustomerDataPritomnost createCustomerDataPritomnost() {
        return new CustomerDataPritomnost();
    }

    /**
     * Create an instance of {@link Vygeneruj }
     * 
     */
    public Vygeneruj createVygeneruj() {
        return new Vygeneruj();
    }

    /**
     * Create an instance of {@link VygenerujResponse }
     * 
     */
    public VygenerujResponse createVygenerujResponse() {
        return new VygenerujResponse();
    }

    /**
     * Create an instance of {@link ArrayOfPristup }
     * 
     */
    public ArrayOfPristup createArrayOfPristup() {
        return new ArrayOfPristup();
    }

    /**
     * Create an instance of {@link Pristup }
     * 
     */
    public Pristup createPristup() {
        return new Pristup();
    }

    /**
     * Create an instance of {@link ArrayOfDochazka }
     * 
     */
    public ArrayOfDochazka createArrayOfDochazka() {
        return new ArrayOfDochazka();
    }

    /**
     * Create an instance of {@link Dochazka }
     * 
     */
    public Dochazka createDochazka() {
        return new Dochazka();
    }

    /**
     * Create an instance of {@link ArrayOfUzivatel }
     * 
     */
    public ArrayOfUzivatel createArrayOfUzivatel() {
        return new ArrayOfUzivatel();
    }

    /**
     * Create an instance of {@link Uzivatel }
     * 
     */
    public Uzivatel createUzivatel() {
        return new Uzivatel();
    }

    /**
     * Create an instance of {@link ArrayOfKategorie }
     * 
     */
    public ArrayOfKategorie createArrayOfKategorie() {
        return new ArrayOfKategorie();
    }

    /**
     * Create an instance of {@link Kategorie }
     * 
     */
    public Kategorie createKategorie() {
        return new Kategorie();
    }

    /**
     * Create an instance of {@link ArrayOfOddeleni }
     * 
     */
    public ArrayOfOddeleni createArrayOfOddeleni() {
        return new ArrayOfOddeleni();
    }

    /**
     * Create an instance of {@link Oddeleni }
     * 
     */
    public Oddeleni createOddeleni() {
        return new Oddeleni();
    }

    /**
     * Create an instance of {@link ArrayOfPritomnost }
     * 
     */
    public ArrayOfPritomnost createArrayOfPritomnost() {
        return new ArrayOfPritomnost();
    }

    /**
     * Create an instance of {@link Pritomnost }
     * 
     */
    public Pritomnost createPritomnost() {
        return new Pritomnost();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QName }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataPristupy }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataPristupy }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "CustomerDataPristupy")
    public JAXBElement<CustomerDataPristupy> createCustomerDataPristupy(CustomerDataPristupy value) {
        return new JAXBElement<CustomerDataPristupy>(_CustomerDataPristupy_QNAME, CustomerDataPristupy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfPristup }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfPristup }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "ArrayOfPristup")
    public JAXBElement<ArrayOfPristup> createArrayOfPristup(ArrayOfPristup value) {
        return new JAXBElement<ArrayOfPristup>(_ArrayOfPristup_QNAME, ArrayOfPristup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pristup }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Pristup }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Pristup")
    public JAXBElement<Pristup> createPristup(Pristup value) {
        return new JAXBElement<Pristup>(_Pristup_QNAME, Pristup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataDochazka }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataDochazka }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "CustomerDataDochazka")
    public JAXBElement<CustomerDataDochazka> createCustomerDataDochazka(CustomerDataDochazka value) {
        return new JAXBElement<CustomerDataDochazka>(_CustomerDataDochazka_QNAME, CustomerDataDochazka.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfDochazka }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfDochazka }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "ArrayOfDochazka")
    public JAXBElement<ArrayOfDochazka> createArrayOfDochazka(ArrayOfDochazka value) {
        return new JAXBElement<ArrayOfDochazka>(_ArrayOfDochazka_QNAME, ArrayOfDochazka.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dochazka }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Dochazka }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Dochazka")
    public JAXBElement<Dochazka> createDochazka(Dochazka value) {
        return new JAXBElement<Dochazka>(_Dochazka_QNAME, Dochazka.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataUzivatele }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataUzivatele }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "CustomerDataUzivatele")
    public JAXBElement<CustomerDataUzivatele> createCustomerDataUzivatele(CustomerDataUzivatele value) {
        return new JAXBElement<CustomerDataUzivatele>(_CustomerDataUzivatele_QNAME, CustomerDataUzivatele.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfUzivatel }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfUzivatel }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "ArrayOfUzivatel")
    public JAXBElement<ArrayOfUzivatel> createArrayOfUzivatel(ArrayOfUzivatel value) {
        return new JAXBElement<ArrayOfUzivatel>(_ArrayOfUzivatel_QNAME, ArrayOfUzivatel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Uzivatel }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Uzivatel }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Uzivatel")
    public JAXBElement<Uzivatel> createUzivatel(Uzivatel value) {
        return new JAXBElement<Uzivatel>(_Uzivatel_QNAME, Uzivatel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfKategorie }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfKategorie }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "ArrayOfKategorie")
    public JAXBElement<ArrayOfKategorie> createArrayOfKategorie(ArrayOfKategorie value) {
        return new JAXBElement<ArrayOfKategorie>(_ArrayOfKategorie_QNAME, ArrayOfKategorie.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Kategorie }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Kategorie }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Kategorie")
    public JAXBElement<Kategorie> createKategorie(Kategorie value) {
        return new JAXBElement<Kategorie>(_Kategorie_QNAME, Kategorie.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfOddeleni }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfOddeleni }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "ArrayOfOddeleni")
    public JAXBElement<ArrayOfOddeleni> createArrayOfOddeleni(ArrayOfOddeleni value) {
        return new JAXBElement<ArrayOfOddeleni>(_ArrayOfOddeleni_QNAME, ArrayOfOddeleni.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Oddeleni }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Oddeleni }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Oddeleni")
    public JAXBElement<Oddeleni> createOddeleni(Oddeleni value) {
        return new JAXBElement<Oddeleni>(_Oddeleni_QNAME, Oddeleni.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataPritomnost }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataPritomnost }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "CustomerDataPritomnost")
    public JAXBElement<CustomerDataPritomnost> createCustomerDataPritomnost(CustomerDataPritomnost value) {
        return new JAXBElement<CustomerDataPritomnost>(_CustomerDataPritomnost_QNAME, CustomerDataPritomnost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfPritomnost }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfPritomnost }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "ArrayOfPritomnost")
    public JAXBElement<ArrayOfPritomnost> createArrayOfPritomnost(ArrayOfPritomnost value) {
        return new JAXBElement<ArrayOfPritomnost>(_ArrayOfPritomnost_QNAME, ArrayOfPritomnost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pritomnost }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Pritomnost }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Pritomnost")
    public JAXBElement<Pritomnost> createPritomnost(Pritomnost value) {
        return new JAXBElement<Pritomnost>(_Pritomnost_QNAME, Pritomnost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypVerifikace }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypVerifikace }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models", name = "TypVerifikace")
    public JAXBElement<TypVerifikace> createTypVerifikace(TypVerifikace value) {
        return new JAXBElement<TypVerifikace>(_TypVerifikace_QNAME, TypVerifikace.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypCinnosti }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypCinnosti }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models", name = "TypCinnosti")
    public JAXBElement<TypCinnosti> createTypCinnosti(TypCinnosti value) {
        return new JAXBElement<TypCinnosti>(_TypCinnosti_QNAME, TypCinnosti.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypUzivatele }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypUzivatele }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models", name = "TypUzivatele")
    public JAXBElement<TypUzivatele> createTypUzivatele(TypUzivatele value) {
        return new JAXBElement<TypUzivatele>(_TypUzivatele_QNAME, TypUzivatele.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "ID", scope = VratPristupy.class)
    public JAXBElement<String> createVratPristupyID(String value) {
        return new JAXBElement<String>(_VratPristupyID_QNAME, String.class, VratPristupy.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "heslo", scope = VratPristupy.class)
    public JAXBElement<String> createVratPristupyHeslo(String value) {
        return new JAXBElement<String>(_VratPristupyHeslo_QNAME, String.class, VratPristupy.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataPristupy }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataPristupy }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "VratPristupyResult", scope = VratPristupyResponse.class)
    public JAXBElement<CustomerDataPristupy> createVratPristupyResponseVratPristupyResult(CustomerDataPristupy value) {
        return new JAXBElement<CustomerDataPristupy>(_VratPristupyResponseVratPristupyResult_QNAME, CustomerDataPristupy.class, VratPristupyResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "ID", scope = VratDochazku.class)
    public JAXBElement<String> createVratDochazkuID(String value) {
        return new JAXBElement<String>(_VratPristupyID_QNAME, String.class, VratDochazku.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "heslo", scope = VratDochazku.class)
    public JAXBElement<String> createVratDochazkuHeslo(String value) {
        return new JAXBElement<String>(_VratPristupyHeslo_QNAME, String.class, VratDochazku.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataDochazka }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataDochazka }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "VratDochazkuResult", scope = VratDochazkuResponse.class)
    public JAXBElement<CustomerDataDochazka> createVratDochazkuResponseVratDochazkuResult(CustomerDataDochazka value) {
        return new JAXBElement<CustomerDataDochazka>(_VratDochazkuResponseVratDochazkuResult_QNAME, CustomerDataDochazka.class, VratDochazkuResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "ID", scope = VratUzivatele.class)
    public JAXBElement<String> createVratUzivateleID(String value) {
        return new JAXBElement<String>(_VratPristupyID_QNAME, String.class, VratUzivatele.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "heslo", scope = VratUzivatele.class)
    public JAXBElement<String> createVratUzivateleHeslo(String value) {
        return new JAXBElement<String>(_VratPristupyHeslo_QNAME, String.class, VratUzivatele.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataUzivatele }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataUzivatele }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "VratUzivateleResult", scope = VratUzivateleResponse.class)
    public JAXBElement<CustomerDataUzivatele> createVratUzivateleResponseVratUzivateleResult(CustomerDataUzivatele value) {
        return new JAXBElement<CustomerDataUzivatele>(_VratUzivateleResponseVratUzivateleResult_QNAME, CustomerDataUzivatele.class, VratUzivateleResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "ID", scope = VratPritomnost.class)
    public JAXBElement<String> createVratPritomnostID(String value) {
        return new JAXBElement<String>(_VratPristupyID_QNAME, String.class, VratPritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "heslo", scope = VratPritomnost.class)
    public JAXBElement<String> createVratPritomnostHeslo(String value) {
        return new JAXBElement<String>(_VratPristupyHeslo_QNAME, String.class, VratPritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataPritomnost }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CustomerDataPritomnost }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "VratPritomnostResult", scope = VratPritomnostResponse.class)
    public JAXBElement<CustomerDataPritomnost> createVratPritomnostResponseVratPritomnostResult(CustomerDataPritomnost value) {
        return new JAXBElement<CustomerDataPritomnost>(_VratPritomnostResponseVratPritomnostResult_QNAME, CustomerDataPritomnost.class, VratPritomnostResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "ID", scope = Vygeneruj.class)
    public JAXBElement<String> createVygenerujID(String value) {
        return new JAXBElement<String>(_VratPristupyID_QNAME, String.class, Vygeneruj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.holypos.com/holyattendance", name = "heslo", scope = Vygeneruj.class)
    public JAXBElement<String> createVygenerujHeslo(String value) {
        return new JAXBElement<String>(_VratPristupyHeslo_QNAME, String.class, Vygeneruj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "CinnostNazev", scope = Pritomnost.class)
    public JAXBElement<String> createPritomnostCinnostNazev(String value) {
        return new JAXBElement<String>(_PritomnostCinnostNazev_QNAME, String.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "KategorieId", scope = Pritomnost.class)
    public JAXBElement<Integer> createPritomnostKategorieId(Integer value) {
        return new JAXBElement<Integer>(_PritomnostKategorieId_QNAME, Integer.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "KategorieNazev", scope = Pritomnost.class)
    public JAXBElement<String> createPritomnostKategorieNazev(String value) {
        return new JAXBElement<String>(_PritomnostKategorieNazev_QNAME, String.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "OddeleniString", scope = Pritomnost.class)
    public JAXBElement<String> createPritomnostOddeleniString(String value) {
        return new JAXBElement<String>(_PritomnostOddeleniString_QNAME, String.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Prichod", scope = Pritomnost.class)
    public JAXBElement<XMLGregorianCalendar> createPritomnostPrichod(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PritomnostPrichod_QNAME, XMLGregorianCalendar.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "TerminalId", scope = Pritomnost.class)
    public JAXBElement<Integer> createPritomnostTerminalId(Integer value) {
        return new JAXBElement<Integer>(_PritomnostTerminalId_QNAME, Integer.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "TerminalNazev", scope = Pritomnost.class)
    public JAXBElement<String> createPritomnostTerminalNazev(String value) {
        return new JAXBElement<String>(_PritomnostTerminalNazev_QNAME, String.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "UzivatelCislo", scope = Pritomnost.class)
    public JAXBElement<String> createPritomnostUzivatelCislo(String value) {
        return new JAXBElement<String>(_PritomnostUzivatelCislo_QNAME, String.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "UzivatelJmeno", scope = Pritomnost.class)
    public JAXBElement<String> createPritomnostUzivatelJmeno(String value) {
        return new JAXBElement<String>(_PritomnostUzivatelJmeno_QNAME, String.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "UzivatelPrijmeni", scope = Pritomnost.class)
    public JAXBElement<String> createPritomnostUzivatelPrijmeni(String value) {
        return new JAXBElement<String>(_PritomnostUzivatelPrijmeni_QNAME, String.class, Pritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Nazev", scope = Oddeleni.class)
    public JAXBElement<String> createOddeleniNazev(String value) {
        return new JAXBElement<String>(_OddeleniNazev_QNAME, String.class, Oddeleni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Nazev", scope = Kategorie.class)
    public JAXBElement<String> createKategorieNazev(String value) {
        return new JAXBElement<String>(_OddeleniNazev_QNAME, String.class, Kategorie.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Cislo", scope = Uzivatel.class)
    public JAXBElement<String> createUzivatelCislo(String value) {
        return new JAXBElement<String>(_UzivatelCislo_QNAME, String.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "DatumNarozeni", scope = Uzivatel.class)
    public JAXBElement<XMLGregorianCalendar> createUzivatelDatumNarozeni(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_UzivatelDatumNarozeni_QNAME, XMLGregorianCalendar.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "EMail", scope = Uzivatel.class)
    public JAXBElement<String> createUzivatelEMail(String value) {
        return new JAXBElement<String>(_UzivatelEMail_QNAME, String.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Heslo", scope = Uzivatel.class)
    public JAXBElement<String> createUzivatelHeslo(String value) {
        return new JAXBElement<String>(_UzivatelHeslo_QNAME, String.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "HodinovaSazba", scope = Uzivatel.class)
    public JAXBElement<BigDecimal> createUzivatelHodinovaSazba(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_UzivatelHodinovaSazba_QNAME, BigDecimal.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Jmeno", scope = Uzivatel.class)
    public JAXBElement<String> createUzivatelJmeno(String value) {
        return new JAXBElement<String>(_UzivatelJmeno_QNAME, String.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Karta", scope = Uzivatel.class)
    public JAXBElement<String> createUzivatelKarta(String value) {
        return new JAXBElement<String>(_UzivatelKarta_QNAME, String.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfKategorie }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfKategorie }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Kategorie", scope = Uzivatel.class)
    public JAXBElement<ArrayOfKategorie> createUzivatelKategorie(ArrayOfKategorie value) {
        return new JAXBElement<ArrayOfKategorie>(_Kategorie_QNAME, ArrayOfKategorie.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfOddeleni }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfOddeleni }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Oddeleni", scope = Uzivatel.class)
    public JAXBElement<ArrayOfOddeleni> createUzivatelOddeleni(ArrayOfOddeleni value) {
        return new JAXBElement<ArrayOfOddeleni>(_Oddeleni_QNAME, ArrayOfOddeleni.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Prijmeni", scope = Uzivatel.class)
    public JAXBElement<String> createUzivatelPrijmeni(String value) {
        return new JAXBElement<String>(_UzivatelPrijmeni_QNAME, String.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Telefon", scope = Uzivatel.class)
    public JAXBElement<String> createUzivatelTelefon(String value) {
        return new JAXBElement<String>(_UzivatelTelefon_QNAME, String.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypUzivatele }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypUzivatele }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "TypUzivatele", scope = Uzivatel.class)
    public JAXBElement<TypUzivatele> createUzivatelTypUzivatele(TypUzivatele value) {
        return new JAXBElement<TypUzivatele>(_UzivatelTypUzivatele_QNAME, TypUzivatele.class, Uzivatel.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "DatumOdchod", scope = Dochazka.class)
    public JAXBElement<XMLGregorianCalendar> createDochazkaDatumOdchod(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DochazkaDatumOdchod_QNAME, XMLGregorianCalendar.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "DatumOdchodSkutecny", scope = Dochazka.class)
    public JAXBElement<XMLGregorianCalendar> createDochazkaDatumOdchodSkutecny(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DochazkaDatumOdchodSkutecny_QNAME, XMLGregorianCalendar.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "DatumPrichod", scope = Dochazka.class)
    public JAXBElement<XMLGregorianCalendar> createDochazkaDatumPrichod(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DochazkaDatumPrichod_QNAME, XMLGregorianCalendar.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "DatumPrichodSkutecny", scope = Dochazka.class)
    public JAXBElement<XMLGregorianCalendar> createDochazkaDatumPrichodSkutecny(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DochazkaDatumPrichodSkutecny_QNAME, XMLGregorianCalendar.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "DochazkaDen_Id", scope = Dochazka.class)
    public JAXBElement<Integer> createDochazkaDochazkaDenId(Integer value) {
        return new JAXBElement<Integer>(_DochazkaDochazkaDenId_QNAME, Integer.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Poznamka", scope = Dochazka.class)
    public JAXBElement<String> createDochazkaPoznamka(String value) {
        return new JAXBElement<String>(_DochazkaPoznamka_QNAME, String.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "TypUzivatelskeCinnosti_Id", scope = Dochazka.class)
    public JAXBElement<Integer> createDochazkaTypUzivatelskeCinnostiId(Integer value) {
        return new JAXBElement<Integer>(_DochazkaTypUzivatelskeCinnostiId_QNAME, Integer.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "UzivatelCislo", scope = Dochazka.class)
    public JAXBElement<String> createDochazkaUzivatelCislo(String value) {
        return new JAXBElement<String>(_PritomnostUzivatelCislo_QNAME, String.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Uzivatel_Id", scope = Dochazka.class)
    public JAXBElement<Integer> createDochazkaUzivatelId(Integer value) {
        return new JAXBElement<Integer>(_DochazkaUzivatelId_QNAME, Integer.class, Dochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "CisloUzivatele", scope = Pristup.class)
    public JAXBElement<String> createPristupCisloUzivatele(String value) {
        return new JAXBElement<String>(_PristupCisloUzivatele_QNAME, String.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Dochazka_Id", scope = Pristup.class)
    public JAXBElement<Integer> createPristupDochazkaId(Integer value) {
        return new JAXBElement<Integer>(_PristupDochazkaId_QNAME, Integer.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "KartaUzivatele", scope = Pristup.class)
    public JAXBElement<String> createPristupKartaUzivatele(String value) {
        return new JAXBElement<String>(_PristupKartaUzivatele_QNAME, String.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Klavesa1", scope = Pristup.class)
    public JAXBElement<Integer> createPristupKlavesa1(Integer value) {
        return new JAXBElement<Integer>(_PristupKlavesa1_QNAME, Integer.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Klavesa2", scope = Pristup.class)
    public JAXBElement<Integer> createPristupKlavesa2(Integer value) {
        return new JAXBElement<Integer>(_PristupKlavesa2_QNAME, Integer.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "KodPrace", scope = Pristup.class)
    public JAXBElement<Integer> createPristupKodPrace(Integer value) {
        return new JAXBElement<Integer>(_PristupKodPrace_QNAME, Integer.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "TerminalId", scope = Pristup.class)
    public JAXBElement<Integer> createPristupTerminalId(Integer value) {
        return new JAXBElement<Integer>(_PritomnostTerminalId_QNAME, Integer.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Uzivatel_Id", scope = Pristup.class)
    public JAXBElement<Integer> createPristupUzivatelId(Integer value) {
        return new JAXBElement<Integer>(_DochazkaUzivatelId_QNAME, Integer.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "VytvorilUzivatel_Id", scope = Pristup.class)
    public JAXBElement<Integer> createPristupVytvorilUzivatelId(Integer value) {
        return new JAXBElement<Integer>(_PristupVytvorilUzivatelId_QNAME, Integer.class, Pristup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfPritomnost }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfPritomnost }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Pritomnost", scope = CustomerDataPritomnost.class)
    public JAXBElement<ArrayOfPritomnost> createCustomerDataPritomnostPritomnost(ArrayOfPritomnost value) {
        return new JAXBElement<ArrayOfPritomnost>(_Pritomnost_QNAME, ArrayOfPritomnost.class, CustomerDataPritomnost.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfUzivatel }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfUzivatel }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Uzivatele", scope = CustomerDataUzivatele.class)
    public JAXBElement<ArrayOfUzivatel> createCustomerDataUzivateleUzivatele(ArrayOfUzivatel value) {
        return new JAXBElement<ArrayOfUzivatel>(_CustomerDataUzivateleUzivatele_QNAME, ArrayOfUzivatel.class, CustomerDataUzivatele.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfDochazka }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfDochazka }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Dochazka", scope = CustomerDataDochazka.class)
    public JAXBElement<ArrayOfDochazka> createCustomerDataDochazkaDochazka(ArrayOfDochazka value) {
        return new JAXBElement<ArrayOfDochazka>(_Dochazka_QNAME, ArrayOfDochazka.class, CustomerDataDochazka.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfPristup }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfPristup }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", name = "Pristupy", scope = CustomerDataPristupy.class)
    public JAXBElement<ArrayOfPristup> createCustomerDataPristupyPristupy(ArrayOfPristup value) {
        return new JAXBElement<ArrayOfPristup>(_CustomerDataPristupyPristupy_QNAME, ArrayOfPristup.class, CustomerDataPristupy.class, value);
    }

}
