//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.12 at 12:20:30 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.karumien.client.adochazka.schemas;
