//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 01:23:44 PM CET 
//


package com.karumien.client.adochazka.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Pritomnost complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pritomnost"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CinnostNazev" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KategorieId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="KategorieNazev" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OddeleniString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Prichod" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="TerminalId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="TerminalNazev" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UzivatelCislo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UzivatelJmeno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UzivatelPrijmeni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pritomnost", propOrder = {
    "cinnostNazev",
    "kategorieId",
    "kategorieNazev",
    "oddeleniString",
    "prichod",
    "terminalId",
    "terminalNazev",
    "uzivatelCislo",
    "uzivatelJmeno",
    "uzivatelPrijmeni"
})
public class Pritomnost {

    @XmlElementRef(name = "CinnostNazev", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cinnostNazev;
    @XmlElementRef(name = "KategorieId", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> kategorieId;
    @XmlElementRef(name = "KategorieNazev", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> kategorieNazev;
    @XmlElementRef(name = "OddeleniString", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> oddeleniString;
    @XmlElementRef(name = "Prichod", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> prichod;
    @XmlElementRef(name = "TerminalId", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> terminalId;
    @XmlElementRef(name = "TerminalNazev", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> terminalNazev;
    @XmlElementRef(name = "UzivatelCislo", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> uzivatelCislo;
    @XmlElementRef(name = "UzivatelJmeno", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> uzivatelJmeno;
    @XmlElementRef(name = "UzivatelPrijmeni", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendance.WS.Customer", type = JAXBElement.class, required = false)
    protected JAXBElement<String> uzivatelPrijmeni;

    /**
     * Gets the value of the cinnostNazev property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCinnostNazev() {
        return cinnostNazev;
    }

    /**
     * Sets the value of the cinnostNazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCinnostNazev(JAXBElement<String> value) {
        this.cinnostNazev = value;
    }

    /**
     * Gets the value of the kategorieId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getKategorieId() {
        return kategorieId;
    }

    /**
     * Sets the value of the kategorieId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setKategorieId(JAXBElement<Integer> value) {
        this.kategorieId = value;
    }

    /**
     * Gets the value of the kategorieNazev property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getKategorieNazev() {
        return kategorieNazev;
    }

    /**
     * Sets the value of the kategorieNazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setKategorieNazev(JAXBElement<String> value) {
        this.kategorieNazev = value;
    }

    /**
     * Gets the value of the oddeleniString property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOddeleniString() {
        return oddeleniString;
    }

    /**
     * Sets the value of the oddeleniString property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOddeleniString(JAXBElement<String> value) {
        this.oddeleniString = value;
    }

    /**
     * Gets the value of the prichod property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getPrichod() {
        return prichod;
    }

    /**
     * Sets the value of the prichod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setPrichod(JAXBElement<XMLGregorianCalendar> value) {
        this.prichod = value;
    }

    /**
     * Gets the value of the terminalId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getTerminalId() {
        return terminalId;
    }

    /**
     * Sets the value of the terminalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setTerminalId(JAXBElement<Integer> value) {
        this.terminalId = value;
    }

    /**
     * Gets the value of the terminalNazev property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTerminalNazev() {
        return terminalNazev;
    }

    /**
     * Sets the value of the terminalNazev property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTerminalNazev(JAXBElement<String> value) {
        this.terminalNazev = value;
    }

    /**
     * Gets the value of the uzivatelCislo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUzivatelCislo() {
        return uzivatelCislo;
    }

    /**
     * Sets the value of the uzivatelCislo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUzivatelCislo(JAXBElement<String> value) {
        this.uzivatelCislo = value;
    }

    /**
     * Gets the value of the uzivatelJmeno property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUzivatelJmeno() {
        return uzivatelJmeno;
    }

    /**
     * Sets the value of the uzivatelJmeno property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUzivatelJmeno(JAXBElement<String> value) {
        this.uzivatelJmeno = value;
    }

    /**
     * Gets the value of the uzivatelPrijmeni property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUzivatelPrijmeni() {
        return uzivatelPrijmeni;
    }

    /**
     * Sets the value of the uzivatelPrijmeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUzivatelPrijmeni(JAXBElement<String> value) {
        this.uzivatelPrijmeni = value;
    }

}
