//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.08 at 07:44:31 PM CEST 
//


package com.karumien.client.adochazka.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypDochazkaDen.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypDochazkaDen"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Normal"/&gt;
 *     &lt;enumeration value="Dovolena"/&gt;
 *     &lt;enumeration value="Lekar"/&gt;
 *     &lt;enumeration value="Nemoc"/&gt;
 *     &lt;enumeration value="NahradniVolno"/&gt;
 *     &lt;enumeration value="SluzebniCesta"/&gt;
 *     &lt;enumeration value="PrekazkaVPraci"/&gt;
 *     &lt;enumeration value="Absence"/&gt;
 *     &lt;enumeration value="OsetrovaniClenaRodiny"/&gt;
 *     &lt;enumeration value="DarovaniKrve"/&gt;
 *     &lt;enumeration value="Pohreb"/&gt;
 *     &lt;enumeration value="HomeOffice"/&gt;
 *     &lt;enumeration value="NeplaceneVolno"/&gt;
 *     &lt;enumeration value="Jednani"/&gt;
 *     &lt;enumeration value="FiremniVolno"/&gt;
 *     &lt;enumeration value="PrekazkaVPraci60"/&gt;
 *     &lt;enumeration value="AbsenceOmluvena"/&gt;
 *     &lt;enumeration value="Svatba"/&gt;
 *     &lt;enumeration value="SickDay"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TypDochazkaDen", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models")
@XmlEnum
public enum TypDochazkaDen {

    @XmlEnumValue("Normal")
    NORMAL("Normal"),
    @XmlEnumValue("Dovolena")
    DOVOLENA("Dovolena"),
    @XmlEnumValue("Lekar")
    LEKAR("Lekar"),
    @XmlEnumValue("Nemoc")
    NEMOC("Nemoc"),
    @XmlEnumValue("NahradniVolno")
    NAHRADNI_VOLNO("NahradniVolno"),
    @XmlEnumValue("SluzebniCesta")
    SLUZEBNI_CESTA("SluzebniCesta"),
    @XmlEnumValue("PrekazkaVPraci")
    PREKAZKA_V_PRACI("PrekazkaVPraci"),
    @XmlEnumValue("Absence")
    ABSENCE("Absence"),
    @XmlEnumValue("OsetrovaniClenaRodiny")
    OSETROVANI_CLENA_RODINY("OsetrovaniClenaRodiny"),
    @XmlEnumValue("DarovaniKrve")
    DAROVANI_KRVE("DarovaniKrve"),
    @XmlEnumValue("Pohreb")
    POHREB("Pohreb"),
    @XmlEnumValue("HomeOffice")
    HOME_OFFICE("HomeOffice"),
    @XmlEnumValue("NeplaceneVolno")
    NEPLACENE_VOLNO("NeplaceneVolno"),
    @XmlEnumValue("Jednani")
    JEDNANI("Jednani"),
    @XmlEnumValue("FiremniVolno")
    FIREMNI_VOLNO("FiremniVolno"),
    @XmlEnumValue("PrekazkaVPraci60")
    PREKAZKA_V_PRACI_60("PrekazkaVPraci60"),
    @XmlEnumValue("AbsenceOmluvena")
    ABSENCE_OMLUVENA("AbsenceOmluvena"),
    @XmlEnumValue("Svatba")
    SVATBA("Svatba"),
    @XmlEnumValue("SickDay")
    SICK_DAY("SickDay");
    private final String value;

    TypDochazkaDen(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypDochazkaDen fromValue(String v) {
        for (TypDochazkaDen c: TypDochazkaDen.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
