//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 12:12:27 AM CEST 
//


package com.karumien.client.adochazka.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypVerifikace.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypVerifikace"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Neznamo"/&gt;
 *     &lt;enumeration value="Heslo"/&gt;
 *     &lt;enumeration value="OtiskPrstu"/&gt;
 *     &lt;enumeration value="CipovaKarta"/&gt;
 *     &lt;enumeration value="Oblicej"/&gt;
 *     &lt;enumeration value="ExterniCtecka"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TypVerifikace", namespace = "http://schemas.datacontract.org/2004/07/HolyAttendanceCore.Models")
@XmlEnum
public enum TypVerifikace {

    @XmlEnumValue("Neznamo")
    NEZNAMO("Neznamo"),
    @XmlEnumValue("Heslo")
    HESLO("Heslo"),
    @XmlEnumValue("OtiskPrstu")
    OTISK_PRSTU("OtiskPrstu"),
    @XmlEnumValue("CipovaKarta")
    CIPOVA_KARTA("CipovaKarta"),
    @XmlEnumValue("Oblicej")
    OBLICEJ("Oblicej"),
    @XmlEnumValue("ExterniCtecka")
    EXTERNI_CTECKA("ExterniCtecka");
    private final String value;

    TypVerifikace(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypVerifikace fromValue(String v) {
        for (TypVerifikace c: TypVerifikace.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
